name: Building
on: 
  pull_request: {}
  push: { branches: [master] }
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  test:
    name: Running tests on project 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
          restore-keys: |
            Library-MyProjectName-
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: tests
        with:
          unityVersion: 2019.4.8f1
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
  build:
    name: Building game for Windows (Server) and WebGL, and uploading new versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneLinux64, WebGL]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      - uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: 2019.4.8f1
          targetPlatform: ${{ matrix.targetPlatform }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-server
          key: ${{ runner.os }}-buildx-${{ github.sha }}-server
          restore-keys: | 
            ${{ runner.os }}-buildx-
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: snuez99/night_in_the_house_of_hunt_server
      - uses: docker/build-push-action@v2
        name: Build server image
        with:
          push: true
          file: server.dockerfile
          context: ./
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache-server
          cache-to: type=local,dest=/tmp/.buildx-cache-server-new
          
          