name: Testing
on: 
  pull_request: {}
  push: { branches: [master] }
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  test:
    name: Running tests on project 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
          restore-keys: |
            Library-MyProjectName-
            Library-
      - uses: webbertakken/unity-test-runner@v1.7
        id: tests
        with:
          unityVersion: 2019.4.8f1
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
  build:
    name: Building game for Linux (Server) and WebGL, and uploading new versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneLinux64, WebGL]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      - uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: 2019.4.8f1
          targetPlatform: ${{ matrix.targetPlatform }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Upload newer client to S3 🔝
        run: aws s3 sync ./build/WebGL/WebGL s3://project-hamilton
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
